name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      solr:
        image: solr:9
        ports:
          - 8983:9001
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with: {python-version: 3.x}
    -  run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install requests
        python -c "import requests; print(requests.__version__)"
        python -c "import requests ; url = 'http://localhost:9001' ; print(url, requests.get(url).status_code)"
        python -c "import requests ; url = 'http://localhost:9001/solr' ; print(url, requests.get(url).status_code)"
        python -c "import requests ; url = 'http://localhost:9001/solr/example' ; print(url, requests.get(url).status_code)" || true
        python -c "import requests ; url = 'http://localhost:9001/solr/collection1' ; print(url, requests.get(url).status_code)" || true
        python -c "import requests ; url = 'http://localhost:9001/solr/collection1/admin' ; print(url, requests.get(url).status_code)" || true
        python -c "import requests ; url = 'http://localhost:9001/solr/collection1/admin/ping' ; print(url, requests.get(url).status_code)" || true
